routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::namespace('admin')->group(function () {
        Route::resource('admin/guru', 'GuruController');
        Route::resource('admin/matapelajaran', 'MatapelajaranController');
        Route::resource('admin/ekstrakulikuler', 'EkstrakulikulerController');
        Route::resource('admin/mengajarmatapelajaran', 'MengajarmatapelajaranController');
        Route::resource('admin/mengajarekstrakulikuler', 'MengajarekstrakulikulerController');
        Route::resource('admin/dataabsenmatapelajaran', 'AbsenmapelController');
        Route::resource('admin/dataabsenekstrakulikuler', 'AbsenekstrakulikulerController');
        Route::resource('admin/user', 'UserController');
        Route::get('/admin', function () {
            return view('admin.index');
        });
    });
});

Route::group(['middleware' => ['auth', 'role:guru']], function () {
    Route::namespace('guru')->group(function () {

        Route::resource('guru/absenmatapelajaran', 'AbsenmapelController');
        Route::resource('guru/absenekstrakulikuler', 'AbsenekstrakulikulerController');
        Route::get('/guru', function () {
            return view('guru.index');
        });
       
    });
});





Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/models/Guru.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Guru extends Model
{
    protected $table="guru";
    protected $primaryKey="id";

    public function mengajarmatapelajaran()
    {
        return $this->hasMany('App\Models\Mengajarmatapelajaran');
    }

    public function absenmatapelajaran()
    {
        return $this->hasManyThrough('App\Models\Absenmapel', 'App\Models\Mengajarmatapelajaran');
    }

    public function mengajarekstrakulikuler()
    {
        return $this->hasMany('App\Models\Mengajarekstrakulikuler');
    }

    public function absenekstrakulikuler()
    {
        return $this->hasManyThrough('App\Models\Absenekstrakulikuler', 'App\Models\Mengajarekstrakulikuler');
    }


    public static function boot() {
        parent::boot();

        static::deleting(function($data) { // before delete() method call this
            $data->mengajarekstrakulikuler()->delete();
            $data->mengajarmatapelajaran()->delete();
            
        });
    }


    
}

app/Http/Controllers/admin/GuruController.php
<?php

namespace App\Http\Controllers\admin;
use App\User;
use App\Models\Guru;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\StoreGuru;
use App\Http\Requests\UpdateGuru;


class GuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.guru.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function getdata()
    {
        $data = Guru::all();


        return Datatables::of($data)
            ->addColumn('action', function ($data) {
                return '
                <a href="guru/'.$data->id.'/edit" class="btn btn-xs btn-primary"><i ></i> Edit</a>
                <a onclick="comfirmdelete('.$data->id.')" class="btn btn-xs btn-danger text-white"><i ></i> Hapus</a>
                ';
            })
            ->make(true);
    }

    public function create()
    {
        return view('admin.guru.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreGuru $request)
    {
        

        //simpan ke user
        $user = new User;
        $user->name=$request->nama;
        $user->email=$request->email;
        $user->password=Hash::make($request->password);
        $user->save();
        $user_id=$user->id;
        
        //memberi role user
        $user->roles()->attach(2);

        //simpan ke guru
        $guru = new Guru;
        $guru->nama = $request->nama;
        $guru->user_id = $user_id;
        $guru->save();
        
        $message = [
            'alert' => 'success',
            'title' => 'Data Berhasil Di Simpan'
        ];
        
        return redirect()->back()->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function show(Guru $guru)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function edit(Guru $guru)
    {

        $user=User::find($guru->user_id);
        $data['guru']=$guru;
        $data['data']=$user;
        return view('admin.guru.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateGuru $request, Guru $guru)
    {


        
        
        $guru = Guru::find($guru->id);

        $guru->nama = $request->nama;

        $guru->save();

        $user = User::find($guru->user_id);

        $user->name=$request->nama;
        

        //jika ubah password
        if($user->email!=$request->email){

            $request->validate([
                'email' => 'required|string|email|max:255|unique:users'
            ]);
            
            $user->email=$request->email;
        }

        if(!empty($request->password)){

            $request->validate([
                'password' => 'required|string|min:6|confirmed'
            ]);
            $user->password=Hash::make($request->password);
            
        }

        $user->save();
        
        
        $message = [
            'alert' => 'success',
            'title' => 'Data Berhasil Di Update'
        ];
        
        return redirect()->back()->with('message', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function destroy(Guru $guru)
    {   
        $user = User::find($guru->user_id);
        $user->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/guru/AbsenekstrakulikulerController.php
<?php

namespace App\Http\Controllers\guru;

use App\Models\Absenekstrakulikuler;
use App\Models\Guru;
use App\Models\Mengajarekstrakulikuler;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AbsenekstrakulikulerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $guru_id=\Auth::user()->guru->id;
        $mengajarekstrakulikuler = Mengajarekstrakulikuler::where('guru_id',$guru_id)->get();
        $data['mengajarekstrakulikuler']=$mengajarekstrakulikuler;
        return view('guru.absenekstrakulikuler.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //simpan ke guru
        $absenekstrakulikuler = new Absenekstrakulikuler;
        $absenekstrakulikuler->mengajarekstrakulikuler_id = $request->mengajarekstrakulikuler;
        $absenekstrakulikuler->save();

        

        $message = [
            'status'=> 'success',
            'alert' => 'success',
            'title' => 'Data Berhasil Di Simpan'
        ];

        return redirect()->back()->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Absenekstrakulikuler  $absenekstrakulikuler
     * @return \Illuminate\Http\Response
     */
    public function show(Absenekstrakulikuler $absenekstrakulikuler)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Absenekstrakulikuler  $absenekstrakulikuler
     * @return \Illuminate\Http\Response
     */
    public function edit(Absenekstrakulikuler $absenekstrakulikuler)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Absenekstrakulikuler  $absenekstrakulikuler
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Absenekstrakulikuler $absenekstrakulikuler)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Absenekstrakulikuler  $absenekstrakulikuler
     * @return \Illuminate\Http\Response
     */
    public function destroy(Absenekstrakulikuler $absenekstrakulikuler)
    {
        //
    }
}

app/Http/Controllers/guru/AbsenmapelController.php
<?php

namespace App\Http\Controllers\guru;

use App\Models\Absenmapel;
use App\Models\Guru;
use App\Models\Mengajarmatapelajaran;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AbsenmapelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $guru_id=\Auth::user()->guru->id;
        $mengajarmatapelajaran = Mengajarmatapelajaran::where('guru_id',$guru_id)->get();
        $data['mengajarmatapelajaran']=$mengajarmatapelajaran;
        return view('guru.absenmatapelajaran.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //simpan ke guru
        $absenmatapelajaran = new Absenmapel;
        $absenmatapelajaran->mengajarmatapelajaran_id = $request->mengajarmatapelajaran;
        $absenmatapelajaran->save();

        

        $message = [
            'status'=> 'success',
            'alert' => 'success',
            'title' => 'Data Berhasil Di Simpan'
        ];

        return redirect()->back()->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Absenmapel  $absenmatapelajaran
     * @return \Illuminate\Http\Response
     */
    public function show(Absenmapel $absenmatapelajaran)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Absenmapel  $absenmatapelajaran
     * @return \Illuminate\Http\Response
     */
    public function edit(Absenmapel $absenmatapelajaran)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Absenmapel  $absenmatapelajaran
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Absenmapel $absenmatapelajaran)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Absenmapel  $absenmatapelajaran
     * @return \Illuminate\Http\Response
     */
    public function destroy(Absenmapel $absenmatapelajaran)
    {
        //
    }
}

resources/views/guru/absenmatapelajaran/index.blade.php
@extends('guru.layouts.default')

@section('title', 'Guru')

@section('content')
    <br>
    <br>
    <div class='container'>

        <div class='card'>
            <div class='card-body'>

                <div class='row'>

                    <div class='col-lg-12'>
                        <p class='h3'>Absen Mata Pelajaran</p>
                    </div>

                    <div class='col-lg-12'>
                        Tanggal : {{date('d-m-Y')}}
                        <hr>
                    </div> 

                    
                    <br>

                    <div class='col-lg-12'>
                        <div class='row justify-content-md-center'>
                            <div class='col-lg-4'>

                                <div class='card bg-light'>
                                    <div class='card-body'>
                                        <form action="{{ route('absenmatapelajaran.store') }}" method="post" enctype="multipart/form-data">
                                            {{csrf_field()}}
                                            

                                            <!-- field -->
                                            <div class="form-group {{ $errors->has('mengajarmatapelajaran') ? 'has-error' : '' }}">
                                                <label for="mengajaramatapelajaran">Mata Pelajaran</label>
                                                <select class="form-control" name="mengajarmatapelajaran">
                                                    @foreach ($mengajarmatapelajaran as $data)
                                                        <option value="{{ $data->id }}" >{{ $data->matapelajaran->nama }}</option>
                                                    @endforeach
                                                </select>
                                                    
                                                @if ($errors->has('bulan'))
                                                    <span class="help-block text-danger">{{ $errors->first('mengajarmatapelajaran') }}</span>
                                                @endif
                                            </div>
                                            <!-- end field -->
                                            
                                            
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-dark w-100">Absen</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            
                            </div>
                        </div>
                                    
                    </div>
                    
                    
                    
                    
                
                
                </div>

            </div>
        </div>
        
        <br>
        

        @if (Session::has('message'))
        <div class="modal" tabindex="-1" role="dialog" id='alert'>
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class='h3'>Absensi Mata Pelajaran Berhasil</p>
                </div>
                <div class="modal-footer">
                    
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
                </div>
            </div>
        </div>

        <script>


            

            $(document).ready( function () {
                
                $('#alert').modal('show')
                
            });
           


        </script>

        @endif

    </div>
    
    
@endsection