routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::namespace('admin')->group(function () {
        Route::resource('admin/guru', 'GuruController');
        Route::resource('admin/matapelajaran', 'MatapelajaranController');
        Route::resource('admin/ekstrakulikuler', 'EkstrakulikulerController');
        Route::resource('admin/mengajarmatapelajaran', 'MengajarmatapelajaranController');
        Route::resource('admin/mengajarekstrakulikuler', 'MengajarekstrakulikulerController');
        Route::resource('admin/dataabsenmatapelajaran', 'AbsenmapelController');
        Route::resource('admin/dataabsenekstrakulikuler', 'AbsenekstrakulikulerController');
        Route::resource('admin/user', 'UserController');
        Route::get('/admin', function () {
            return view('admin.index');
        });
    });
});

Route::group(['middleware' => ['auth', 'role:guru']], function () {
    Route::namespace('guru')->group(function () {

        Route::resource('guru/absenmatapelajaran', 'AbsenmapelController');
        Route::resource('guru/absenekstrakulikuler', 'AbsenekstrakulikulerController');
        Route::get('/guru', function () {
            return view('guru.index');
        });
       
    });
});





Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/absenmatapelajaran/dataabsen.blade.php
<table class='table table-responsive table-bordered'>
    <thead>
            
                    <tr>
                        <th width="200px" rowspan="2">
                            Guru
                        </th>
            
                        <th width="200px" rowspan="2">
                            Mata Pelajaran
                        </th>
            
            
                        <th colspan="{{$jumlah_hari}}">
                            Tanggal
                        </th>
                        
            
                        <th rowspan='2'>
                            Total
                        </th>
                    </tr>
                    <tr>
                        
        
            
                        @for ($i = 1; $i <= $jumlah_hari; $i++)
                            <th width="40px">
                                {{$i}}
                            </th>
                        @endfor
            
                       
                    </tr>
                </thead>
            
                <tbody>
            
                    @foreach($absen as $absen)
            
                    <tr>
                        <td>
                            {{$absen['nama_guru']}}
                        </td>
            
            
                        <td>
                            {{$absen['mata_pelajaran']}}
                        </td>
            
                        
                        @php

                            $total=0;
                        @endphp

                        

                        @for ($i = 1; $i <= $jumlah_hari; $i++)
                            <td align="center">
                                {{$absen['absen'][$i]}}
                            </td>

                            @php
                                if(!empty($absen['absen'][$i])){

                                    $total=$total+$absen['absen'][$i];

                                }
                                
                            @endphp
                        @endfor
                        
                        <td align="center">
                            {{$total}}
                        </td>
                        
            
            
                    <tr>
            
            
                    @endforeach
                
                </tbody>
    
   
</table>

resources/views/admin/absenmatapelajaran/dataabsenguru.blade.php
<p class='h3'>Nama Guru : {{$guru['nama']}}</p>

<table class='table table-responsive table-bordered'>
    <thead>
        <tr>
            <th colspan='@php echo count($guru["absen"]) @endphp'>
                Tanggal
            </th>
                
            <th rowspan='2'>
                total
            </th>
        </tr>

        <tr>

        
        @foreach($guru['absen'] as $dataabsen)
            <th>
                {{$dataabsen['tanggal']}}
            </th>
        @endforeach
            
        </tr>
    </thead>

    <tbody>

    
        <tr>
            @php $total=0; @endphp
            @foreach($guru['absen'] as $dataabsen)
                <td>
                    {{$dataabsen['jumlah']}}
                </td>
                @php $total +=$dataabsen['jumlah']; @endphp
            @endforeach
                <td>
                    {{$total}}
                </td>
        </tr>
    </tbody>
    
   
</table>

resources/views/admin/absenmatapelajaran/datatableguru.blade.php
<table class="table table-bordered" id="tabel-guru">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nama</th>
            <th>Action</th>
            
        </tr>
    </thead>
</table>

<script>
$(document).ready( function () {
    $('#tabel-guru').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url('api/admin/absenmatapelajaran/getdataguru') }}',
        columns: [
            {data:'id'},
            {data:'nama'},
            {data:'action', orderable: false, searchable: false}
        ]
    });
});

</script>

resources/views/admin/absenmatapelajaran/index.blade.php
@extends('admin.layouts.default')

@section('title', 'Absen Mata Pelajaran')

@section('content')
    
    <div class='row'>
        <div class='col-lg-12'>
            
        </div>
        
        
    </div>
    <br>
    @if($start==false)
    <div class='row'>
        <div class='col-lg-12'>
            @include('admin.absenmatapelajaran.searchform')
        </div>
        
    </div>
    <hr>

    
            
           
    @else

    <div class='row'>
        <div class='col'>
            <a class="btn btn-dark" href="{{ route('dataabsenmatapelajaran.index') }}" role="button">Kembali</a>
            <a class='btn btn-dark text-white' href="{{ url('admin/dataabsenmatapelajaran/?bulan='.$bulan.'&tahun='.$tahun.'&cetak=true')}}">Cetak</a>
        
        </div>

        
        
        
    </div>
    <br>
    <br>

    
    <div class='row'>
        <div class='col-lg-12'>
            

            @include('admin.absenmatapelajaran.dataabsen')
            
           

        </div>
    @endif

        
    </div>
    <br>


    
    
@endsection

resources/views/admin/absenmatapelajaran/searchform.blade.php
<form>
            <div class="row">  
                <div class="col">
                <select class="form-control" name="bulan">
                    <option value='1'

                        @if (isset($bulan))
                            @if ($bulan==1)
                                selected
                            @endif
                            
                        @endif
                    
                    >Januari
                    </option>
                    <option value='2'

                        @if (isset($bulan))
                            @if ($bulan==2)
                                selected
                            @endif
                            
                        @endif
                    
                    >Februari
                    </option>
                    <option value='3'

                        @if (isset($bulan))
                            @if ($bulan==3)
                                selected
                            @endif
                            
                        @endif
                    
                    >Maret
                    </option>

                    <option value='4'

                        @if (isset($bulan))
                            @if ($bulan==4)
                                selected
                            @endif
                            
                        @endif
                    
                    >April
                    </option>

                    <option value='5'

                        @if (isset($bulan))
                            @if ($bulan==5)
                                selected
                            @endif
                            
                        @endif
                    
                    >Mei
                    </option>

                    <option value='6'

                        @if (isset($bulan))
                            @if ($bulan==6)
                                selected
                            @endif
                            
                        @endif
                    
                    >Juni
                    </option>

                    <option value='7'

                        @if (isset($bulan))
                            @if ($bulan==7)
                                selected
                            @endif
                            
                        @endif
                    
                    >Juli
                    </option>

                    <option value='8'

                        @if (isset($bulan))
                            @if ($bulan==8)
                                selected
                            @endif
                            
                        @endif
                    
                    >Agustus
                    </option>

                    <option value='9'

                        @if (isset($bulan))
                            @if ($bulan==9)
                                selected
                            @endif
                            
                        @endif
                    
                    >September
                    </option>

                    <option value='10'

                        @if (isset($bulan))
                            @if ($bulan==10)
                                selected
                            @endif
                            
                        @endif
                    
                    >Oktober
                    </option>

                    <option value='11'

                        @if (isset($bulan))
                            @if ($bulan==11)
                                selected
                            @endif
                            
                        @endif
                    
                    >November
                    </option>

                    <option value='12'

                        @if (isset($bulan))
                            @if ($bulan==12)
                                selected
                            @endif
                            
                        @endif
                    
                    >Desember
                    </option>
                    

                </select>
                </div>
               
                <div class="col">
                <select class="form-control" name="tahun">
                    @for ($i = 2018; $i <= 2030; $i++)
                    
                    <option value='{{$i}}'

                        @if (isset($bulan))
                            @if ($bulan==$i)
                                selected
                            @endif
                            
                        @endif
                    
                    >{{$i}}
                    </option>
                    @endfor
                </select>
                </div>
            </div>
            <br>
            <div class="row">

                <div class="col-lg-4">
                    <input type="submit" class="btn btn-dark form-control" value='Cari'>
                </div>
                
            </div>
        </form>

resources/views/admin/absenmatapelajaran/show.blade.php
@extends('admin.layouts.default')

@section('title', 'Absen Mata Pelajaran')

@section('content')
    
    <div class='row'>
        <div class='col-lg-12'>
            
        </div>
        
        
    </div>
    <br>
    

    <div class='row'>
        <div class='col'>
            <a class="btn btn-dark" href="{{ route('dataabsenmatapelajaran.index') }}" role="button">Kembali</a>
            <a class='btn btn-dark text-white' href="{{ url('admin/dataabsenmatapelajaran/'.$guru['guru_id'].'?bulan='.$bulan.'&tahun='.$tahun.'&cetak=true')}}">Cetak</a>
        </div>
        
        
    </div>
    <br>
    <br>

    
    <div class='row'>
        <div class='col-lg-12'>
            

            @include('admin.absenmatapelajaran.dataabsenguru')

           

        </div>
    

        
    </div>
    <br>


    <div class="modal" tabindex="-1" role="dialog" id='modalcomfirmdelete'>
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Komfirmasi Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method='post' id="formhapus">
                    @method('DELETE')
                    {{csrf_field()}}
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger">Ya Hapus</button>
                        
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
    </div>

    <script>


        function comfirmdelete(id){

            $(document).ready( function () {
                
                $('#modalcomfirmdelete').modal('show')
               
            });
        }


    </script>
    
@endsection