routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::namespace('admin')->group(function () {
        Route::resource('admin/guru', 'GuruController');
        Route::resource('admin/matapelajaran', 'MatapelajaranController');
        Route::resource('admin/ekstrakulikuler', 'EkstrakulikulerController');
        Route::resource('admin/mengajarmatapelajaran', 'MengajarmatapelajaranController');
        Route::resource('admin/mengajarekstrakulikuler', 'MengajarekstrakulikulerController');
        Route::resource('admin/dataabsenmatapelajaran', 'AbsenmapelController');
        Route::resource('admin/dataabsenekstrakulikuler', 'AbsenekstrakulikulerController');
        Route::resource('admin/user', 'UserController');
        Route::get('/admin', function () {
            return view('admin.index');
        });
    });
});

Route::group(['middleware' => ['auth', 'role:guru']], function () {
    Route::namespace('guru')->group(function () {

        Route::resource('guru/absenmatapelajaran', 'AbsenmapelController');
        Route::resource('guru/absenekstrakulikuler', 'AbsenekstrakulikulerController');
        Route::get('/guru', function () {
            return view('guru.index');
        });
       
    });
});





Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



    public function roleuser()
    {
        return $this->hasMany('App\Roleuser');
    }

    public function guru()
    {
        return $this->hasOne('App\Models\Guru');
    }

    

    // this is a recommended way to declare event handlers
    public static function boot() {
        parent::boot();

        static::deleting(function($user) { // before delete() method call this
            $user->guru()->delete();
        });
    }

    

}

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use App\User;
use App\Roleuser;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Yajra\Datatables\Datatables;

use App\Http\Requests\StoreUser;
use App\Http\Requests\UpdateUser;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function getdata()
    {
        $data = Roleuser::with('user')->with('role')->where('role_id',1)->get();


        return Datatables::of($data)
            ->addColumn('action', function ($data) {
                return '
                <a href="user/'.$data->user_id.'/edit" class="btn btn-xs btn-primary"><i ></i> Edit</a>
                <a onclick="comfirmdelete('.$data->user_id.')" class="btn btn-xs btn-danger text-white"><i ></i> Hapus</a>
                ';
            })
            ->make(true);
    }

    public function create()
    {

        $data['role'] = Role::all();
        return view('admin.user.create',$data);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
        
        $user = new User;
        $user->name=$request->username;
        $user->email=$request->email;
        $user->password=Hash::make($request->password);
        $user->save();
        $user_id=$user->id;
        
        //memberi role user
        $user->roles()->attach($request->role);

        $message = [
            'alert' => 'success',
            'title' => 'Data Berhasil Di Simpan'
        ];
        
        return redirect()->back()->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        
        
        $data['role'] = Role::all();
        $data['user']=Roleuser::where('user_id',$user->id)->with('user')->with('role')->get();
        
        
        
        
        
       
        
        return view('admin.user.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUser $request, User $user)
    {
        
        $user = User::find($user->id);

        $user->name=$request->username;
        
        //jika ubah password
        if($user->email!=$request->email){

            $request->validate([
                'email' => 'required|string|email|max:255|unique:users'
            ]);
            
            $user->email=$request->email;
        }

        if(!empty($request->password)){

            $request->validate([
                'password' => 'required|string|min:6|confirmed'
            ]);
            $user->password=Hash::make($request->password);
            
        }

        $user->save();


        $destroy=Roleuser::where('user_id',$user->id)->delete();
        $user->roles()->attach($request->role);
        
        $message = [
            'alert' => 'success',
            'title' => 'Data Berhasil Di Update'
        ];
        
        return redirect()->back()->with('message', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        User::destroy($user->id);
        $destroy=Roleuser::where('user_id',$user->id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.default')

@section('title', 'Tambah user')

@section('content')
   
    
    {{-- part alert --}}
    @if (Session::has('message'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-dismissible alert-{{ Session::get('message.alert') }}">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ Session::get('message.title') }}</strong>
                    
                </div>
            </div>
        </div>
    @endif
    
    <form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
        {{csrf_field()}}
        

        <!-- field -->
        <div class="form-group {{ $errors->has('username') ? 'has-error' : '' }}">
            <label for="username" class="control-label">Username</label>
            <input type="text" class="form-control" name="username" placeholder="username">
            @if ($errors->has('username'))
                <span class="help-block text-danger">{{ $errors->first('username') }}</span>
            @endif
        </div>
        <!-- end field -->

        <!-- field -->
        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
            <label for="email" class="control-label">Email</label>
            <input type="email" class="form-control" name="email" placeholder="email">
            @if ($errors->has('email'))
                <span class="help-block text-danger">{{ $errors->first('email') }}</span>
            @endif
        </div>
        <!-- end field -->

        <!-- field -->
        <div class="form-group {{ $errors->has('role') ? 'has-error' : '' }}">
            <label for="role" class="control-label">Level</label>
            <select class="form-control" name="role">
                @foreach ($role as $value)
                    <option value='{{ $value->id }}'>{{ $value->display_name }}</option>
                @endforeach
            </select>
            @if ($errors->has('role'))
                <span class="help-block text-danger">{{ $errors->first('role') }}</span>
            @endif
        </div>
        <!-- end field -->
        
        <div class="form-group">
            <label for="password" class="control-label">{{ __('Password') }}</label>

            
            <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

            @if ($errors->has('password'))
                <span class="help-block text-danger" role="alert">
                   {{ $errors->first('password') }}
                </span>
            @endif
            
        </div>

        <div class="form-group">
            <label for="password-confirm" class="control-label">{{ __('Confirm Password') }}</label>

            
            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
            
        </div>

        
        
        
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Simpan</button>
            <a href="{{ route('user.index') }}" class="btn btn-default">Kembali</a>
        </div>
    </form>

@endsection

resources/views/admin/user/datatable.blade.php
<table class="table table-bordered" id="tabel-user">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nama User</th>
            <th>Email</th>
            <th>Level</th>
            <th>Action</th>
            
        </tr>
    </thead>
</table>

<script>
$(document).ready( function () {
    $('#tabel-user').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url('api/user/getdata') }}',
        columns: [
            {data:'user_id'},
            {data:'user.name'},
            {data:'user.email'},
            {data:'role.display_name'},
            {data:'action', orderable: false, searchable: false}
        ]
    });
});

</script>

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.default')

@section('title', 'Edit Kriteria Dan Bobot')

@section('content')
   
    
    {{-- part alert --}}
    @if (Session::has('message'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-dismissible alert-{{ Session::get('message.alert') }}">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ Session::get('message.title') }}</strong>
                    
                </div>
            </div>
        </div>
    @endif
    
    @foreach($user as $user)
    <form action='{{ route("user.update",["id" => $user->user_id]) }}' method="POST">
        @method('PUT')
        {{csrf_field()}}
        
        
        <!-- field -->
        <div class="form-group {{ $errors->has('username') ? 'has-error' : '' }}">
            <label for="username" class="control-label">Username</label>
            <input type="text" class="form-control" name="username" placeholder="username" value='{{$user->user->name}}'>
            @if ($errors->has('username'))
                <span class="help-block text-danger">{{ $errors->first('username') }}</span>
            @endif
        </div>
        <!-- end field -->

        <!-- field -->
        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
            <label for="email" class="control-label">Email</label>
            <input type="email" class="form-control" name="email" placeholder="email" value='{{$user->user->email}}'>
            @if ($errors->has('email'))
                <span class="help-block text-danger">{{ $errors->first('email') }}</span>
            @endif
        </div>
        <!-- end field -->

        <!-- field -->
        <div class="form-group {{ $errors->has('role') ? 'has-error' : '' }}">
            <label for="role" class="control-label">Level</label>
            <select class="form-control" name="role">
                @foreach ($role as $value)
                    <option value='{{ $value->id }}'
                    
                    @if ($value->id==$user->role_id)
                        selected
                    @endif    
                    
                    
                    >{{ $value->display_name }}</option>
                @endforeach
            </select>
            @if ($errors->has('role'))
                <span class="help-block text-danger">{{ $errors->first('role') }}</span>
            @endif
        </div>
        <!-- end field -->
        
        <div class="form-group">
            <label for="password" class="control-label">{{ __('Password') }}</label>

            
            <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password">

            @if ($errors->has('password'))
                <span class="help-block text-danger" role="alert">
                   {{ $errors->first('password') }}
                </span>
            @endif
            
        </div>

        <div class="form-group">
            <label for="password-confirm" class="control-label">{{ __('Confirm Password') }}</label>

            
            <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
            
        </div>

        
        
        
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
            <a href="{{ route('user.index') }}" class="btn btn-default">Kembali</a>
        </div>
    </form>
   
    @endforeach


    

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.default')

@section('title', 'User Mangement')

@section('content')
    
    <div class='row'>
        <div class='col'>
            <a class="btn btn-primary" href="{{ route('user.create') }}" role="button">Tambah Data</a>
        </div>
        
        
    </div>
    <br>
    <div class='row'>
        <div class='col'>
            @include('admin.user.datatable')
        </div>
        
    </div>


    <div class="modal" tabindex="-1" role="dialog" id='modalcomfirmdelete'>
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Komfirmasi Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method='post' id="formhapus">
                    @method('DELETE')
                    {{csrf_field()}}
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger">Ya Hapus</button>
                        
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
    </div>

    <script>


        function comfirmdelete(id){

            $(document).ready( function () {
                url="{{ url('admin/user/') }}"+'/'+id;
                $('#modalcomfirmdelete').modal('show')
                $("#formhapus").attr("action", url);
            });
        }


    </script>
    
@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.default')

@section('title', 'Kriteria Dan Bobot')

@section('content')
    <div class='row'>
        <div class='col'>

            <h4>{{ $guru->id_guru }}</h4>
            <p>{{ $guru->nama_guru }}</p>
            <a href="{{ route('guru.index') }}" class="btn btn-default">Kembali</a>
        </div>
        
    </div>
    

    

@endsection